require("dotenv").config({ path: "../.env" });
const connectDB = require("../config/db");

const mongoose = require("mongoose");
const Scheme = require("../models/Scheme"); 



const schemesData = [
  {
    id: 1,
    name: "Startup India (DPIIT Recognition)",
    shortName: "DPIIT Recognition",
    category: "government-of-india",
    oneLiner: "DPIIT Recognition is the official recognition provided by the Department for Promotion of Industry and Internal Trade (DPIIT), Government of India, which certifies an entity as a “Startup” and unlocks tax exemptions, funding access, IPR benefits, and regulatory relaxations.",
    description: "Official DPIIT certification unlocking tax exemptions, IPR fast-tracking, funding eligibility, and easier compliance.",
    fullDescription: "Flagship recognition providing 100% tax exemption (3 years), angel tax relief, IPR rebates/fast-tracking, tender exemptions, and self-certification benefits.",
    detailedBenefits: [
      "Income Tax Exemption – Section 80-IAC: 100% income tax exemption for any 3 consecutive financial years within the first 10 years of incorporation",
      "Angel Tax Exemption (Section 56): Investments raised above Fair Market Value (FMV) are not taxed",
      "IPR Support: 80% rebate on patent filing fees, 50% rebate on trademark filing, Fast-track patent examination, Government-appointed IPR facilitators (free of cost)",
      "Tenders & PSU Opportunities: No prior experience, No turnover requirement, EMD exemption",
      "Easy compliance: Self-certification under labour & environment laws",
    ],
    detailedEligibility: [
      "Entity Type: Private Limited Company, LLP, or Registered Partnership Firm (Sole proprietorships/unregistered not eligible)",
      "Age: Less than 10 years from incorporation",
      "Turnover: Not exceeding ₹100 crore in any financial year",
      "Business Nature: Innovative, improving existing products/services, or scalable model with high employment/wealth potential",
      "Original Entity: Not formed by splitting/reconstructing existing business or rebranding",
    ],
    applicationProcess: [
      "Step 1: Register on Startup India Portal - https://www.startupindia.gov.in, Register/Login, Verify email/OTP",
      "Step 2: Login and complete profile",
      "Step 3: Create NSWS Account - https://www.nsws.gov.in, Register as Startup",
      "Step 4: Add “Registration as a Startup” approval",
      "Step 5: Fill entity details, startup profile (problem, solution, innovation/scalability), funding/awards",
      "Step 6: Upload documents: Certificate of Incorporation, PAN, Address proof, Innovation write-up, Optional pitch deck/website",
      "Step 7: Self-declaration and submit (No fees; Typically approved in 2 working days)",
    ],
    documentsRequired: [
      "Certificate of Incorporation",
      "PAN of entity",
      "Founder/Director details",
      "Business address proof",
      "Innovation & scalability write-up",
      "Website/app link (if any)",
    ],
    applyUrl: "https://www.startupindia.gov.in",
    processingTime: "2 working days (upon successful submission)",
    keyPoints: [
      "Over 1.74 lakh recognitions issued as of 2025",
      "Prerequisite for most other schemes",
      "Active and unchanged core criteria as of December 2025",
    ],
  },
  {
    id: 2,
    name: "Startup India Seed Fund Scheme (SISFS)",
    shortName: "SISFS",
    category: "government-of-india",
    oneLiner: "Startup India Seed Fund Scheme (SISFS) is a Government of India initiative to provide early-stage financial assistance to startups for idea validation, prototype development, product trials, market entry, and commercialization.",
    description: "Early-stage grant/debt via incubators for DPIIT-recognized startups.",
    fullDescription: "₹945 crore scheme (2021-2025) providing up to ₹20 lakh grant + ₹50 lakh debt/convertible; applications ongoing.",
    detailedBenefits: [
      "Grant up to ₹20 lakh for prototype/PoC/MVP/testing/validation/pilots",
      "Debt/convertible up to ₹50 lakh for market entry/commercialization/scaling",
      "Incubation, mentorship, investor/demo day exposure",
      "No government equity dilution",
      "Milestone-based disbursement",
      "Sector-agnostic",
    ],
    detailedEligibility: [
      "DPIIT-recognized",
      "Incorporated ≤2 years",
      "Indian origin with innovative/scalable model",
      "Prior government funding ≤₹10 lakh",
      "Clear milestones & fund use",
    ],
    applicationProcess: [
      "Step 1: Login to https://www.startupindia.gov.in/",
      "Step 2: Navigate to https://seedfund.startupindia.gov.in/, Apply Now",
      "Step 3: Select preferred incubators (up to multiple)",
      "Step 4: Upload pitch deck, business plan, fund utilization",
      "Step 5: Incubator evaluation (possible presentation/Q&A)",
      "Step 6: Approval & agreement",
      "Step 7: Milestone-based disbursement",
    ],
    documentsRequired: [
      "DPIIT Recognition Certificate",
      "Certificate of Incorporation",
      "Founder KYC (Aadhaar, PAN)",
      "Pitch Deck",
      "Detailed Business Plan",
      "Fund Utilization Plan",
      "Milestone roadmap",
      "Bank Details",
      "Incubator preference",
    ],
    applyUrl: "https://seedfund.startupindia.gov.in/",
    processingTime: "8-12 weeks",
    keyPoints: [
      "Ongoing applications (active as of December 2025)",
      "Supported thousands of startups via 300+ incubators",
    ],
  },
  {
    id: 3,
    name: "Fund of Funds for Startups (FFS – SIDBI)",
    shortName: "FFS – SIDBI",
    category: "government-of-india",
    oneLiner: "Fund of Funds for Startups (FFS) is a flagship Government of India initiative to provide equity funding support to startups indirectly through SEBI-registered AIFs.",
    description: "Indirect equity via government-supported AIFs/VCs.",
    fullDescription: "Corpus expanded to ₹20,000 crore (Budget 2025); supports AIFs investing in startups.",
    detailedBenefits: [
      "Access to large equity (₹1-25+ crore via VCs)",
      "No direct government equity/control",
      "Higher credibility & follow-on chances",
    ],
    detailedEligibility: [
      "DPIIT-recognized",
      "Scalable, innovation-driven, high-growth",
      "Typically seed to Series B",
      "Sector-agnostic",
    ],
    applicationProcess: [
      "Step 1: Ensure DPIIT recognition",
      "Step 2: Check SIDBI-backed AIFs at https://www.sidbivcf.in/en/funds/ffs",
      "Step 3: Pitch directly to relevant VCs/AIFs",
      "Step 4: VC due diligence & independent investment",
    ],
    documentsRequired: [
      "DPIIT Recognition Certificate",
      "Certificate of Incorporation",
      "Pitch Deck",
      "Financials/Projections",
      "Cap table",
      "Founder profiles",
      "Traction metrics",
    ],
    applyUrl: "https://www.sidbivcf.in/en/funds/ffs",
    processingTime: "3-6 months (VC-dependent)",
    keyPoints: [
      "Corpus ₹20,000 crore (additional ₹10,000 crore in Budget 2025)",
      "Supported 1,100+ startups as of 2025",
      "Active and expanded",
    ],
  },
  {
    id: 4,
    name: "Credit Guarantee Scheme for Startups (CGSS)",
    shortName: "CGSS",
    category: "government-of-india",
    oneLiner: "Credit Guarantee Scheme for Startups (CGSS) is a Government of India initiative to help startups raise bank loans without collateral with government guarantee.",
    description: "Collateral-free debt with guarantee cover up to ₹20 crore.",
    fullDescription: "Expanded in 2025: Guarantee up to ₹20 crore, higher cover %, reduced fees for champion sectors.",
    detailedBenefits: [
      "Collateral-free loans up to ₹20 crore",
      "Guarantee: 85% up to ₹10 crore, 75% above",
      "Easier approvals, retain ownership",
      "Working capital/term loans/venture debt",
    ],
    detailedEligibility: [
      "DPIIT-recognized",
      "Operational with viable model",
      "Not NPA",
      "Business purpose only",
    ],
    applicationProcess: [
      "Online: Jan Samarth Portal https://www.jansamarth.in/",
      "Offline: Approach Member Lending Institutions (banks/NBFCs/AIFs)",
    ],
    documentsRequired: [
      "DPIIT Recognition Certificate",
      "Certificate of Incorporation",
      "PAN & GST (if applicable)",
      "Founder KYC",
      "Loan application",
      "Business plan & revenue model",
      "Financial projections (2–3 years)",
      "Bank statements",
      "Existing loans (if any)",
    ],
    applyUrl: "https://www.jansamarth.in/",
    processingTime: "15-30 days",
    keyPoints: [
      "Expanded to ₹20 crore limit (May 2025 notification)",
      "Reduced AGF for champion sectors",
      "Active as of December 2025",
    ],
  },
  {
    id: 5,
    name: "Pradhan Mantri MUDRA Yojana (PMMY)",
    shortName: "PMMY",
    category: "government-of-india",
    oneLiner: "Pradhan Mantri MUDRA Yojana (PMMY) is a Government of India scheme that provides collateral-free loans to micro and small businesses.",
    description: "Collateral-free micro loans up to ₹20 lakh.",
    fullDescription: "Categories: Shishu (₹50k), Kishore (₹5L), Tarun (₹10L), Tarun Plus (₹20L for repeat borrowers).",
    detailedBenefits: [
      "Collateral-free up to ₹20 lakh",
      "Wide network (banks/NBFCs/MFIs)",
      "Flexible use: Working capital, equipment, expansion",
      "Low documentation",
    ],
    detailedEligibility: [
      "Indian citizen",
      "Non-farm micro/small enterprise",
      "New/existing (non-agricultural)",
    ],
    applicationProcess: [
      "Apply via https://www.mudra.org.in/ or banks/NBFCs",
      "Choose category (Shishu/Kishore/Tarun/Tarun Plus)",
      "Submit form & documents",
    ],
    documentsRequired: [
      "Aadhaar Card",
      "PAN Card",
      "Business address proof",
      "Bank account details",
      "Simple business plan/form",
      "Quotations (if applicable)",
      "Photographs",
    ],
    applyUrl: "https://www.mudra.org.in/",
    processingTime: "7-15 days",
    keyPoints: [
      "Tarun Plus category: Up to ₹20 lakh (introduced 2024, active 2025)",
      "Ideal for micro/early-stage",
    ],
  },
  {
    id: 6,
    name: "SAMRIDH Scheme (MeitY)",
    shortName: "SAMRIDH",
    category: "government-of-india",
    oneLiner: "SAMRIDH is a flagship startup acceleration scheme launched by the Ministry of Electronics and Information Technology (MeitY). The scheme supports software product startups through funding + structured acceleration via empanelled accelerators.",
    description: "Funding up to ₹40 lakh + acceleration for software product startups.",
    fullDescription: "Matching grant with accelerators; second cohort launched, ongoing calls.",
    detailedBenefits: [
      "Up to ₹40 lakh (50% MeitY + 50% accelerator)",
      "6-12 month structured program",
      "Mentoring (business/product/GTM/legal)",
      "Market access (enterprise/PSU pilots)",
      "Investor readiness & demo days",
    ],
    detailedEligibility: [
      "Indian software product company",
      "Working product, early traction/pilots",
      "DPIIT recognition preferred",
    ],
    applicationProcess: [
      "Check https://www.meity.gov.in/samridh for empanelled accelerators",
      "Search/apply for active accelerator cohorts",
      "Apply directly via accelerator website",
    ],
    documentsRequired: [
      "Certificate of Incorporation",
      "DPIIT Certificate (if available)",
      "Pitch Deck",
      "Product demo/access",
      "Business & revenue model",
      "Financial projections",
      "Founder profiles",
      "Bank details",
    ],
    applyUrl: "https://www.meity.gov.in/samridh",
    processingTime: "Accelerator-dependent (6-12 weeks)",
    keyPoints: [
      "Second cohort active (2024-2025)",
      "Apply through accelerators only",
    ],
  },
  {
    id: 7,
    name: "MSME Innovative / Incubation Scheme",
    shortName: "MSME Innovative",
    category: "government-of-india",
    oneLiner: "Grant support for MSMEs working on innovation and commercialization through incubation, design, and IPR.",
    description: "Integrated support for prototype, design, IPR commercialization.",
    fullDescription: "Unified scheme with grants up to ₹15 lakh incubation + design/IPR reimbursement.",
    detailedBenefits: [
      "Incubation grant up to ₹15 lakh",
      "Prototype & pilot funding",
      "IPR reimbursement",
      "Industry/market linkage via incubators",
    ],
    detailedEligibility: [
      "Udyam-registered MSME",
      "Innovative product/service",
      "Indian entity",
    ],
    applicationProcess: [
      "Visit https://innovative.msme.gov.in/",
      "Apply under relevant component (Incubation/Design/IPR)",
      "Select host institution/incubator",
      "Proposal evaluation & approval",
    ],
    documentsRequired: [
      "Udyam registration",
      "Project proposal",
      "Bank account details",
    ],
    applyUrl: "https://innovative.msme.gov.in/",
    processingTime: "6-8 weeks",
    keyPoints: [
      "Active integrated scheme as of 2025",
      "Focus on commercialization",
    ],
  },
  {
    id: 8,
    name: "Biotechnology Ignition Grant (BIG) – BIRAC, DBT",
    shortName: "BIG",
    category: "government-of-india",
    oneLiner: "Biotechnology Ignition Grant (BIG) is an early-stage grant funding scheme to support high-risk, high-potential biotech innovations.",
    description: "Up to ₹50 lakh grant for PoC/prototype in biotech.",
    fullDescription: "Non-repayable grant over 18 months with mentorship; biannual calls.",
    detailedBenefits: [
      "Grant up to ₹50 lakh for PoC/prototype/lab validation/early development",
      "Mentorship & networking via BIG partners",
      "Regulatory/commercialization guidance",
    ],
    detailedEligibility: [
      "Indian citizen/entity",
      "Early-stage (pre-revenue/early revenue)",
      "Novel biotech innovation with commercial potential",
      "DPIIT preferred for companies",
    ],
    applicationProcess: [
      "Check active calls on https://birac.nic.in/big.php (typically Jan/July)",
      "Register on BIRAC portal",
      "Fill online proposal (applicant/project/technical/team/budget details)",
      "Upload documents & submit",
      "Evaluation: Screening, expert review, presentation, selection",
    ],
    documentsRequired: [
      "Detailed Project Proposal",
      "Abstract & technical summary",
      "Work plan & milestones",
      "Budget utilization",
      "CVs of team",
      "Aadhaar/PAN",
      "Incorporation/DPIIT (if company)",
      "Incubator LOI (if needed)",
    ],
    applyUrl: "https://birac.nic.in/big.php",
    processingTime: "4-6 months post-call",
    keyPoints: [
      "25th call open until Nov 30, 2025",
      "Biannual calls active",
    ],
  },
  {
    id: 10,
    name: "GENESIS (Gen-Next Support for Innovative Startups) – MeitY / NSTEDB",
    shortName: "GENESIS",
    category: "government-of-india",
    oneLiner: "GENESIS is a national initiative to support early-stage to growth-stage tech startups through funding, incubation, mentoring, and ecosystem access.",
    description: "Umbrella support for tech startups, focus on Tier-II/III cities.",
    fullDescription: "₹490 crore scheme consolidating MeitY startup programs; funding varies by component.",
    detailedBenefits: [
      "Variable funding for early scaling/pilots",
      "Mentorship & ecosystem access",
      "Alignment with national digital priorities",
    ],
    detailedEligibility: [
      "Indian tech startup (digital/emerging tech)",
      "Incorporated (Pvt Ltd/LLP)",
      "DPIIT preferred",
      "Early traction/MVP/pilot-ready",
      "Sectors: AI/ML, SaaS, FinTech, HealthTech, etc.",
    ],
    applicationProcess: [
      "Apply through GENESIS-supported incubators/accelerators",
      "Check https://www.meity.gov.in/schemes/genesis for partners",
      "Submit via incubator program/call",
    ],
    documentsRequired: [
      "Certificate of Incorporation",
      "DPIIT Certificate (if available)",
      "Pitch Deck",
      "Founder profiles",
      "Product/demo link",
      "Business model & revenue plan",
      "Financial projections",
      "Bank details",
    ],
    applyUrl: "https://www.meity.gov.in/schemes/genesis",
    processingTime: "Incubator-dependent",
    keyPoints: [
      "Active with EiR & pilot components in 2025",
      "Focus on Tier-II/III",
    ],
  },
  // MP State Schemes (from previous accurate data)
   {
    id: 28,
    name: "MP Startup Policy (2025)",
    shortName: "MP Startup Policy 2025",
    category: "state-government-madhya-pradesh",
    oneLiner: "MP Startup Policy (2025) is the flagship state policy to support startups through financial incentives, operational support, IP benefit, marketing assistance, tender preference, and ecosystem strengthening.",
    description: "Comprehensive incentive package for DPIIT-recognized startups operating in Madhya Pradesh.",
    fullDescription: "Offers seed funding, sustenance allowance, IPR reimbursement, marketing support, lease/utility subsidy, and tender preference — all through a single portal.",
    detailedBenefits: [
      "Seed funding up to ₹30 lakh for product development, testing, commercialization",
      "Monthly sustenance allowance for eligible startups during incubation",
      "IPR cost reimbursement",
      "Marketing & branding support",
      "Utility / Lease subsidy",
      "Tender preference in government procurement",
    ],
    detailedEligibility: [
      "DPIIT-recognized startup",
      "Incorporated as Private Limited Company, LLP, or Partnership (as per DPIIT)",
      "Entity operating in Madhya Pradesh",
      "Innovative and scalable product/service",
    ],
    applicationProcess: [
      "STEP 1: Visit https://startupmp.mygov.co.in/",
      "STEP 2: Register / Sign Up → Verify via OTP → Login",
      "STEP 3: Complete detailed startup profile (basic info, founders, business model, upload documents)",
      "STEP 4: Go to “Apply for Benefits” → Choose specific incentive (Seed Funding, Patent, Marketing, etc.)",
      "STEP 5: Fill incentive-specific form + upload supporting documents",
      "STEP 6: Submit application → Receive Application ID",
      "STEP 7: Track status from dashboard",
    ],
    documentsRequired: [
      "DPIIT recognition certificate",
      "Certificate of Incorporation",
      "PAN & GST (if applicable)",
      "Startup pitch deck",
      "Bank account details",
      "Incentive-specific: Patent receipts/draft, event quotes, rent receipts, use of funds plan, etc.",
    ],
    applyUrl: "https://startupmp.mygov.co.in/",
    processingTime: "4–10 weeks (varies by incentive)",
    keyPoints: [
      "Single unified portal for all benefits",
      "Notified / active in 2025",
      "Prerequisite: DPIIT recognition",
    ],
  },

  {
    id: 29,
    name: "Mukhya Mantri Yuva Udyami Yojana",
    shortName: "MM Yuva Udyami Yojana",
    category: "state-government-madhya-pradesh",
    oneLiner: "Mukhya Mantri Yuva Udyami Yojana provides bank loans with government facilitation and support to young entrepreneurs (18–40 years) for starting or expanding manufacturing, service, or trading businesses in Madhya Pradesh.",
    description: "Youth-focused loan scheme with structured bank routing and state facilitation.",
    fullDescription: "Loan up to ₹2 crore routed through banks with faster screening; final terms depend on bank appraisal.",
    detailedBenefits: [
      "Loan range: ₹10 lakh to ₹2 crore (project-based)",
      "For new setup, expansion, working capital + fixed assets",
      "Government facilitation and faster preliminary screening",
      "Eligible sectors: Manufacturing, Services, Trading (non-agricultural)",
    ],
    detailedEligibility: [
      "Resident of Madhya Pradesh",
      "Age: Generally 18–40 years",
      "Not a bank defaulter",
      "Viable project in manufacturing/service/trading",
    ],
    applicationProcess: [
      "STEP 1: Visit https://www.merayuva.mp.gov.in/",
      "STEP 2: Register/Login using mobile & email + OTP",
      "STEP 3: Go to Schemes → Select Mukhya Mantri Yuva Udyami Yojana",
      "STEP 4: Fill online application (personal, business & project details)",
      "STEP 5: Upload required documents",
      "STEP 6: Submit → Get Application ID",
      "STEP 7: Application routed to district authority & empanelled bank → Bank appraisal → Sanction",
    ],
    documentsRequired: [
      "Aadhaar Card",
      "PAN Card",
      "MP Domicile/Residence proof",
      "Detailed Project Report / Business Plan",
      "Quotations for machinery/equipment (if applicable)",
      "Bank account details",
      "GST & registration (if existing business)",
    ],
    applyUrl: "https://www.merayuva.mp.gov.in/",
    processingTime: "30–90 days (mostly depends on bank appraisal)",
    keyPoints: [
      "Youth entrepreneurship flagship scheme",
      "Bank-driven final sanction",
      "Active as of 2025–26",
    ],
  },

  {
    id: 30,
    name: "Mukhyamantri Udyam Kranti Yojana",
    shortName: "MM Udyam Kranti Yojana",
    category: "state-government-madhya-pradesh",
    oneLiner: "Mukhyamantri Udyam Kranti Yojana promotes self-employment by providing collateral-free / low-collateral bank loans (up to ₹50 lakh) with state facilitation for small businesses in manufacturing, services, and trading.",
    description: "Self-employment loan scheme with wider coverage and smaller ticket sizes compared to Yuva Udyami.",
    fullDescription: "Loan support from ₹50,000 to ₹50 lakh; digital routing through MSME portal.",
    detailedBenefits: [
      "Loan range: ₹50,000 to ₹50 lakh",
      "New setup, expansion, machinery, working capital",
      "State government facilitation & preliminary screening",
    ],
    detailedEligibility: [
      "Permanent resident of Madhya Pradesh",
      "Age generally 18–45 years",
      "Individual / Proprietorship / Partnership / Company / LLP",
      "Not a bank defaulter",
      "Viable project in manufacturing/service/trading",
    ],
    applicationProcess: [
      "STEP 1: Visit https://msme.mponline.gov.in/",
      "STEP 2: Register / Login",
      "STEP 3: Search for Mukhyamantri Udyam Kranti Yojana",
      "STEP 4: Click Apply Online",
      "STEP 5: Fill personal + business + project details",
      "STEP 6: Upload documents",
      "STEP 7: Submit → Application routed to MSME office / bank",
      "STEP 8: Verification → Loan sanction",
    ],
    documentsRequired: [
      "Aadhaar Card",
      "PAN Card",
      "MP Domicile proof",
      "Project Report / Business Plan",
      "Quotations for machinery (if any)",
      "Bank account details",
      "GST & business registration (if applicable)",
    ],
    applyUrl: "https://msme.mponline.gov.in/",
    processingTime: "30–75 days",
    keyPoints: [
      "Suitable for micro & small enterprises",
      "Wider age & entity coverage",
      "Active through MPOnline/MSME portal",
    ],
  },

  {
    id: 31,
    name: "Mukhya Mantri Krishak Udyami Yojana",
    shortName: "MM Krishak Udyami Yojana",
    category: "state-government-madhya-pradesh",
    oneLiner: "Mukhya Mantri Krishak Udyami Yojana promotes entrepreneurship among farmers’ family members by providing capital subsidy and interest subsidy on bank loans for setting up non-agricultural businesses.",
    description: "Special scheme for farmers’ families with attractive subsidy support.",
    fullDescription: "Capital subsidy up to ₹18 lakh + interest subsidy up to 6% for 7 years; higher benefits for reserved categories & special groups.",
    detailedBenefits: [
      "Capital Subsidy: 15–30% (max ₹1–18 lakh depending on category & project size)",
      "Interest Subsidy: 5–6% p.a. for max 7 years",
      "Higher benefits for BPL, SC/ST, women, minorities, disabled, nomadic tribes, Bhopal gas victims",
      "Guarantee fee support",
    ],
    detailedEligibility: [
      "Age 18–45 years",
      "Minimum 10th pass",
      "Permanent resident of Madhya Pradesh",
      "Parents should NOT own agricultural land",
      "Family should NOT be income tax payer",
      "Not availing any other self-employment scheme",
      "Not a bank defaulter",
    ],
    applicationProcess: [
      "Online: Visit https://msme.mponline.gov.in/ → Register/Login → Apply for Mukhya Mantri Krishak Udyami Yojana",
      "Offline: Download form → Fill → Attach documents → Submit at Farmer Welfare Dept / District Trade & Industry Centre",
      "Verification by department → Approval & benefit disbursement",
    ],
    documentsRequired: [
      "Aadhaar Card",
      "PAN Card",
      "Birth certificate / 10th marksheet",
      "MP Domicile / Address proof",
      "Income certificate",
      "BPL certificate (if applicable)",
      "Land farming paper (parents)",
      "Passport size photo",
    ],
    applyUrl: "https://msme.mponline.gov.in/",
    processingTime: "45–120 days (varies by verification)",
    keyPoints: [
      "Targeted at landless farmers’ families",
      "Very attractive subsidy structure",
      "Both online & offline application modes available",
    ],
  },
  // International Schemes
  {
    id: 19,
    name: "Startup India – International Engagements (International Bridges)",
    shortName: "International Bridges",
    category: "international",
    oneLiner: "Startup India – International Engagements (International Bridges) is a government-facilitated initiative under Startup India that forges strategic global partnerships, bilateral and multilateral collaborations to help Indian startups gain exposure, knowledge exchange, mentorship, networking, and access to international markets through structured global bridges with partner countries and organisations.",
    description: "Global partnerships, market access, and ecosystem exposure for Indian startups.",
    fullDescription: "Curated international opportunities via Startup India portal for cross-border collaborations and events.",
    detailedBenefits: [
      "Global exposure and access to international startup ecosystems",
      "Opportunities for cross-border partnerships and collaborations",
      "Interaction with global mentors, investors, and industry experts",
      "Participation in international startup events, forums, and showcases",
      "Learning of global best practices and market-entry strategies",
    ],
    detailedEligibility: [
      "Indian startups registered on the Startup India portal",
      "DPIIT-recognised startups are preferred",
      "Startups with innovative, scalable solutions aligned to global markets",
      "Eligibility may vary depending on specific international events or collaborations",
    ],
    applicationProcess: [
      "Step 1: Register on Startup India Portal - Create an account on the Startup India portal, Complete your startup profile and indicate DPIIT recognition (if applicable)",
      "Step 2: Explore International Opportunities on the Portal - Navigate to “International Engagements” under Market Access / Global Collaborations, Review ongoing bridges and collaboration programmes",
      "Step 3: Subscribe or Contact for More Details - Use the contact form on the International Engagement page to express interest, or call the Startup India National Toll Free Number: 1800 115 565",
      "Step 4: Respond to Curated Event Invitations - Based on your profile and relevance, Startup India and ecosystem partners may invite startups to participate in upcoming international programmes",
      "Step 5: Prepare for Participation - For selected events, global missions, or bilateral programmes, follow the event-specific submission requirements (which may include: Pitch deck, Business plan, Market entry strategy)",
    ],
    documentsRequired: [
      "DPIIT Startup Recognition Certificate (preferred)",
      "Company/entity registration documents",
      "Startup pitch deck and basic business information",
      "Founder or team details",
      "Some programmes may request proof of concept, market traction, or demo credentials depending on the host country’s participation guidelines",
    ],
    applyUrl: "https://www.startupindia.gov.in/content/sih/en/international.html",
    processingTime: "Varies by event (curated invitations)",
    keyPoints: [
      "No separate application form; participation is curated",
      "Ongoing opportunities as of December 2025",
      "Focus on bilateral/multilateral bridges",
    ],
  },
  {
    id: 20,
    name: "Google for Startups Accelerator",
    shortName: "Google Accelerator",
    category: "international",
    oneLiner: "Google for Startups Accelerator is a global, equity-free accelerator program by Google that provides startups with tailored mentorship, technical guidance, access to Google products and ecosystem experts to help them grow and scale their business.",
    description: "Equity-free acceleration with mentorship, cloud credits, and global exposure.",
    fullDescription: "Tailored programs for India cohort; up to $350,000 in cloud credits for early-stage startups.",
    detailedBenefits: [
      "Equity-free support: For duration of program",
      "Technical mentorship and expert guidance from Google teams and industry professionals",
      "Access to tailored accelerator programs that help refine product design, customer acquisition strategies, and leadership skills",
      "Google Cloud credits and product credits, reducing infrastructure costs and enabling technical scaling",
      "Participation in workshops, networking events, and community bootcamps that connect founders to broader startup ecosystems",
      "Exposure to global growth opportunities and potential investor/partner interactions through program-related showcases and demo days",
      "Early access to AI products: Eligible participants receive Early Access Program and Trusted Tester benefits for Google’s AI products",
      "Early stage startups can get up to $350,000 in Cloud credits through the Google for Startups Cloud Program, and Series B+ startups can continue scaling with customized support and solutions",
      "Cloud TPUs: Participants are eligible to receive free Cloud TPU access to accelerate open source machine learning research",
    ],
    detailedEligibility: [
      "Startups demonstrating traction, ideally between Seed and Series A stage",
      "Building a scalable product or service with a significant total addressable market and defensible growth model",
      "Deeply technical, preferably leveraging technologies like machine learning and AI",
      "Commitment from CTO and/or technical roles to participate and engage in required program sessions",
      "For Cloud and Product Support Tiers: Startups at various stages (from early to equity-funded) can qualify for cloud credits and product credits based on funding history and growth stage",
      "Eligibility may differ depending on the specific regional cohort or programme tier",
    ],
    applicationProcess: [
      "Step 1: Explore and Choose the Right Program - Visit the official programme listings to identify the appropriate initiative for your startup: Google for Startups Programs, Review Programme Details, Select the specific accelerator or support programme (e.g., India Accelerator, Cloud Program) and review eligibility, timelines, and requirements",
      "Step 2: Prepare Your Application Materials - Ensure you have the required documents (startup profile, team info, pitch deck, technical and funding details, Google Cloud Billing ID if required)",
      "Step 3: Submit Through the Official Form - Click on the “Apply” button on the programme page and complete the application form with accurate and compelling information. Applications often involve: Startup details, Business description, Product overview, Market potential, Team background",
      "Step 4: Evaluation & Shortlisting - Submitted applications are reviewed by a panel of experts or the programme team. Shortlisted startups may be invited for interviews or pitch sessions as part of the selection process",
      "Step 5: Final Selection & Participation - If selected, startups engage in the programme schedule, including mentorship sessions, training, workshops, and networking activities",
    ],
    documentsRequired: [
      "Incorporation / registration documents",
      "Company website or domain",
      "Founder / key team member profiles",
      "Contact and role details",
      "Pitch deck covering value proposition, problem solved, business model",
      "Technical description of product or solution",
      "Proof of equity funding for certain accelerator tiers or cloud credits programmes",
      "A valid Google Cloud billing account ID",
      "Email domain that matches the startup’s website domain (for credit allocation)",
    ],
    applyUrl: "https://startup.google.com/programs/accelerator/india/",
    processingTime: "4-6 weeks (application review and selection)",
    keyPoints: [
      "Equity-free with focus on AI/ML tech startups",
      "India-specific cohort active as of 2025",
      "Includes cloud credits up to $350K",
    ],
  },
  {
    id: 21,
    name: "PayU for Startups Program",
    shortName: "PayU Startups",
    category: "international",
    oneLiner: "PayU for Startups is a dedicated initiative by PayU to support early-stage startups by providing simplified payment solutions, exclusive offers, waived fees, mentoring support, and fintech resources to help them scale their digital payments infrastructure.",
    description: "Payment gateway integration with discounts, credits, and mentorship for startups.",
    fullDescription: "Zero-setup fees, exclusive partner offers worth up to ₹3.5 lakhs, and access to 150+ payment methods.",
    detailedBenefits: [
      "Zero-setup / discounted payment gateway integration - Helps startups accept online payments without upfront costs",
      "Exclusive Partner Offers - MixPanel (free first year), Zoho (₹1,86,000 credits), Zolvit (50% off legal/tax), Skill Connect (discounted job postings), Zyvka (AI hiring discounts), HDFC Bank (business credit card), Briefcase AI (legal guidance savings up to ₹3.5 Lakhs), We Work (₹4,000/month workspace savings), Hero Vired (25% off certifications)",
      "Preferential pricing / reduced transaction fees - Lower payment processing fees compared to standard commercial rates",
      "$100K in Startup Credits for incorporation, banking, office spaces, CRM tools, & more",
      "Avail FREE 1:1 Mentorship from experts across marketing, product, tech, D2C & more",
      "Scale with 150+ payment methods, EMI/BNPL, and global payment methods",
      "Access to PayU’s payment products - Including payment gateway, links, subscriptions, invoicing, and payout services",
      "Dedicated support and onboarding assistance - With onboarding help from PayU relationship managers",
      "Startup ecosystem support & mentoring - Connects startups with networks through corporate and partner events",
      "Access to analytics and payment optimization tools - To help improve conversion and monitor customer behavior",
    ],
    detailedEligibility: [
      "Startup must be registered in India",
      "Offering products or services with online payments",
      "Must have a formal legal entity (e.g., Pvt Ltd, LLP, Partnership, Sole Proprietorship)",
      "Preferably DPIIT-recognized (recommended, though not always mandatory)",
      "Have a functional website/app where payments will be accepted",
    ],
    applicationProcess: [
      "Step 1: Visit the Startup Program Page - Go to the PayU for Startups partner page or dedicated startup support page where PayU lists offers for startups",
      "Step 2: Click on Get Started - Fill out: Startup name, Business type, Website / product URL, Contact details (email & phone). This leads to onboarding communications",
      "Step 3: Documentation Submission - Upload or email the required official documents listed earlier",
      "Step 4: PayU Evaluation & Onboarding - PayU team reviews the application, verifies documents, and enables the startup account with applicable preferential pricing and offers",
    ],
    documentsRequired: [
      "Company registration certificate (e.g., CIN / registration details)",
      "PAN card of the entity",
      "Bank account details with canceled cheque",
      "Authorized signatory identity proof (e.g., Aadhaar / Passport / Voter ID)",
      "Website / app URL where payments will be integrated",
      "Cancelled cheque or bank letter for payout setup",
      "DPIIT recognition certificate (if claiming startup offers)",
    ],
    applyUrl: "https://www.startups.payu.in/",
    processingTime: "2-4 weeks (onboarding and verification)",
    keyPoints: [
      "Tailored for fintech/payment-integrated startups",
      "Exclusive offers worth up to ₹3.5 lakhs",
      "Active global program as of December 2025",
    ],
  },
  {
    id: 22,
    name: "IndiaAI Startups Global Acceleration Program with Station F and HEC Paris",
    shortName: "IndiaAI Global Acceleration",
    category: "international",
    oneLiner: "The IndiaAI Startups Global Acceleration Program is a 4-month international acceleration initiative, led by the IndiaAI Mission (Ministry of Electronics and IT) in collaboration with Station F (Paris, France) and HEC Paris, designed to help Indian AI startups scale globally through mentorship, market access, and ecosystem immersion.",
    description: "4-month program (1 month online + 3 months onsite in Paris) for AI startups with funded travel and accommodation.",
    fullDescription: "Selects 10 AI startups; covers program fees, travel, accommodation (excl. visa, daily allowances, food).",
    detailedBenefits: [
      "Global Market Exposure: Immersive opportunity to access European markets and startup ecosystems",
      "Structured Mentorship: Guidance from world-class mentors, experts, and investor networks associated with Station F and HEC Paris",
      "Acceleration Support: Strategic business development, product-market fit refinement, and cross-border collaboration facilitation",
      "Funded Participation: Program fees, travel, and accommodation supported by IndiaAI Mission (visa fees and daily consumables are generally borne by the startup)",
      "Dedicated Residency: A 1-month online phase followed by 3 months onsite at Station F, the world’s largest startup campus, with access to workspace and community resources",
      "Investor and Network Access: Engagements with European investors, ecosystem partners, and potential strategic collaborators",
    ],
    detailedEligibility: [
      "Startup Stage: Early-stage to Series C",
      "Sector: AI solutions addressing significant challenges",
      "Market Traction: Demonstrated domestic traction (e.g., customers, revenue, partnerships)",
      "Global Vision: Strong potential for European and Global market entry",
      "Legal Status: Registered as a company in India",
      "Team Strength: Competent founding team with technical and business expertise",
    ],
    applicationProcess: [
      "Step 1: Visit IndiaAI Portal - Complete a detailed application form hosted on the IndiaAI portal. The form collects: Business details, Market traction, Team composition, Strategic goals for European market entry, etc.; among various sections",
      "Step 2: Submit Application - For Queries, Contact Us: gm-startups@indiaai.gov.in",
      "Step 3: Evaluation and Selection - Shortlisting based on application; possible interviews",
      "Step 4: Onboarding - Selected startups prepare for online phase followed by onsite residency",
    ],
    documentsRequired: [
      "Business details and incorporation documents",
      "Market traction evidence (revenue, customers, partnerships)",
      "Team composition and founder profiles",
      "Strategic goals for European market entry",
      "Product demo or pitch deck",
    ],
    applyUrl: "https://indiaai.gov.in/indiaaiportal",
    processingTime: "6-8 weeks (application to selection)",
    keyPoints: [
      "10 startups selected per cohort",
      "Funded by IndiaAI Mission; active in 2025",
      "Focus on AI for global scaling",
    ],
  },
  {
    id: 23,
    name: "UAE-India Start-Up Series – CEPA Council Initiative",
    shortName: "UAE-India Series",
    category: "international",
    oneLiner: "The UAE-India Start-Up Series is a flagship cross-border startup acceleration and market access initiative under the UAE-India CEPA Council, designed to connect high-potential Indian startups with the UAE innovation ecosystem to support global scaling, mentorship, and soft-landing opportunities.",
    description: "Acceleration with UAE soft-landing, mentorship, and funded travel for top 5 selected startups.",
    fullDescription: "Selects top 5 from 500+ applicants; includes incubation, investor intros, and logistics support.",
    detailedBenefits: [
      "Market entry support in the UAE through incubation and ecosystem integration",
      "Soft-landing package including incubation at a UAE accelerator, mentorship, and access to investors and ecosystem partners",
      "Fully supported participation logistics such as round-trip flights, hotel stay, local transport, and meal support during the UAE programme phase for the final selected startups",
      "Networking and commercial partnership opportunities through partnerships with UAE innovation hubs and CEPA Council partners",
    ],
    detailedEligibility: [
      "Be an Indian-registered startup entity (company/LLP/incorporated business demonstrate innovation, business viability, and product/service readiness",
      "Have traction or a clear roadmap for UAE engagement or international expansion",
      "Be capable of participating in multiple evaluation stages including written application, pitch deck submission, and round-table pitch events",
    ],
    applicationProcess: [
      "Step 1: Online Application Submission - Visit the official program page, Click “Apply / Application Form” on the homepage or menu, Fill in the required details: Startup name, registration, sector, Founder info, contact, team size, Product/service description, Market opportunity & target customers, Current traction or validation, Expansion/ambition for UAE market",
      "Step 2: Confirmation & Screening - After submission, the CEPA Council team reviews basic eligibility. Evaluation parameters at this stage include: Innovation level, Problem–solution clarity, Founding team capability, Global scalability potential",
      "Step 3: Top 500 Shortlisting (National Level) - Top 500 startups are selected from all applications. They receive email confirmation and instructions for the next round. These startups are required to submit a Pitch Deck for further evaluation",
      "Step 4: Pitch Deck Submission & Evaluation - Pitch deck must generally include: Problem & solution, Business model, Market size, Go-to-market strategy, Team competency, Why UAE market? (international expansion thesis), Traction, revenue (if any), Tech/IP differentiator. The evaluation panel shortlists the Top 20 based on the pitch deck",
      "Step 5: Top 20 → Final Pitch Round - Virtual or in-person pitching round (Delhi / designated venue), Panel members include: CEPA Council representatives, UAE innovation partners, Investors/mentors. Evaluation focuses on: UAE market readiness, Investor potential, Scalability & feasibility, Execution capability",
      "Step 6: Final 5 Selection - Five startups are selected for the Soft-Landing Program in the UAE. Official announcements are made via: Website, Email to founders, Press & media releases",
      "Step 7: UAE Soft-Landing & Onboarding - Selected startups receive: Incubation placement in a UAE innovation hub, Business mentoring & investor introductions, Travel support (round-trip flights, hotel stay, local transport, meals), Meetings for market entry & partnership development, UAE regulatory and business setup guidance",
    ],
    documentsRequired: [
      "Founder & Team Details - Names, emails, team bios, number of full-time members, roles",
      "Product / Service Description - Clear description of the problem being solved, target customers, and how the product addresses the need (up to ~500 words)",
      "Market & Scalability Plan - Target market, growth plans, expansion strategy for the next 1–2 years",
      "Traction & Validation - Current metrics, usage data, business/revenue model",
    ],
    applyUrl: "https://start-upseries.cepacouncil.com",
    processingTime: "8-12 weeks (multi-stage selection)",
    keyPoints: [
      "Top 5 get UAE soft-landing with full logistics",
      "Anchored in UAE-India CEPA; sector-agnostic",
      "Active cohorts in 2025",
    ],
  },
  {
    id: 24,
    name: "G20 Startup20",
    shortName: "Startup20",
    category: "international",
    oneLiner: "G20 Startup20 is the official engagement group under the G20 framework, established during India’s 2023 presidency to represent the global startup ecosystem, unite stakeholders, and formulate policy recommendations that support innovation, entrepreneurship, and cross-border startup collaboration across G20 nations.",
    description: "Policy forum for global startup ecosystem influence, networking, and showcases.",
    fullDescription: "Engagement group with task forces on foundation, finance, inclusion; no direct funding but policy impact.",
    detailedBenefits: [
      "Global Policy Influence - Shape G20 recommendations on startup ecosystems",
      "Networking with founders, investors, governments across G20 nations",
      "Participation in summits, workshops, and task forces",
      "Showcase opportunities for innovative startups",
      "Cross-border collaboration and alliances",
    ],
    detailedEligibility: [
      "Participation typically occurs through invitations, event registrations, ecosystem partnerships, and stakeholder nominations from member countries",
      "Key participants come from: Startup founders, Investors, Ecosystem organisations (incubators/accelerators), Government startup ecosystem representatives",
      "Startups with demonstrated ecosystem leadership, innovation, or impact may be invited to showcase, speak, or participate in specific events (e.g., Startup20 summits or taskforce consultations)",
    ],
    applicationProcess: [
      "Step 1: Visit the Official Website - Go to the official G20 Startup20 platform, Navigate to sections such as: Showcase Your Startup",
      "Step 2: Fill the Relevant Interest / Participation Form - Typical information requested: Applicant type (startup / founder / ecosystem), Company / organisation credentials, Profile and role, Sector and geography, Why you want to participate (objective), Contribution you can make to Startup20 discussions or showcases. No sales pitch / funding ask required, focus is on: Ecosystem value, Policy relevance, Collaboration intent",
      "Step 3: Internal Review by Startup20 Team - Your submission is evaluated based on: Relevance to G20 innovation themes, Strength of profile or sector alignment, Policy or cross-border collaboration potential, Diversity and representation. This step ensures alignment with the global policy mission of Startup20",
      "Step 4: Invitation or Follow-Up Request - If shortlisted, you may receive: Invitation to attend an event, Request for pitch deck / profile, Nomination for taskforce committee, Invitation to submit a policy note, Opportunity to speak at a forum. This depends on the category you applied for. Participation may lead to inclusion in: Summit delegations, Closed-door taskforce policy sessions, Global networking roundtables, Country-specific working groups",
      "Step 5: Attend Programmes / Contribute - If accepted, participants engage through: Summits (regional/global), Workshops, Policy‐construction meetings, Founder showcases, Cross-border delegation visits",
    ],
    documentsRequired: [
      "Company / organisation credentials",
      "Profile and role details",
      "Sector and geography information",
      "Statement on participation objective and contribution",
      "Optional: Pitch deck or policy note",
    ],
    applyUrl: "https://g20startup20.org",
    processingTime: "4-6 weeks (review to invitation)",
    keyPoints: [
      "Task forces on Foundation, Finance, Inclusion & Sustainability",
      "Policy communiqué to G20 leaders",
      "Ongoing engagement post-India presidency; active 2025",
    ],
  },
  {
    id: 25,
    name: "Zayed Sustainability Prize",
    shortName: "Zayed Prize",
    category: "international",
    oneLiner: "The Zayed Sustainability Prize is the UAE's pioneering global award that recognises and rewards small to medium sized enterprises (SMEs), nonprofit organisations (NPOs), and global high schools with impactful, innovative, and inspiring sustainable solutions.",
    description: "Global award with up to USD 600,000 grants for sustainable innovations in health, food, energy, water, climate.",
    fullDescription: "Annual prize across 6 categories; winners announced at Abu Dhabi Sustainability Week.",
    detailedBenefits: [
      "Up to USD 600,000 grant prize per category (USD 100,000 per school region for Global High Schools)",
      "Global recognition and international visibility",
      "Access to global sustainability networks, partners, and mentors",
      "Platform to scale solutions in new markets and communities",
    ],
    detailedEligibility: [
      "Registered SMEs, nonprofit organisations, or high schools with a working solution",
      "Solution must show impact, innovation, and inspiration",
      "Must fit into one category: Health, Food, Energy, Water, Climate Action, or Global High Schools",
      "Project must demonstrate capacity to scale and benefit communities",
    ],
    applicationProcess: [
      "Step 1: Visit the Official Prize Website - Start by going to the official portal: Here you can find information about categories, guidelines, deadlines, FAQs, and how to apply",
      "Step 2: Understand Categories & Choose the Right One - The Prize invites submissions across six categories: Health — Sustainable healthcare solutions, Food — Food security and sustainable agriculture, Energy — Clean, affordable, renewable energy, Water — Safe drinking water, sanitation and water efficiency, Climate Action — Climate resilience and environmental solutions, Global High Schools — Student-led sustainability projects (regional)",
      "Step 3: Prepare for Submission - Before applying: a) Register on the Online Portal - You must create an account on the Prize’s official submissions portal. All entries are submitted online; there is no alternative method (email/post). b) Select the Appropriate Category - Choose the category that best fits your organisation/project",
      "Step 4: Complete the Online Application Form - Once registered: 1. Log into the submissions portal 2. Select your chosen category 3. Fill out the online form with: Organisation/project details, Description of your solution, Impact, innovation and inspiration narrative, Long-term vision and sustainability plan 4. Upload supporting documents as attachments (PDF/Word/JPG)",
      "Step 5: Attach Supporting Materials - When applying, you may include: Project documentation, Videos (YouTube/Vimeo link), Evidence of impact, Financial documents or plans (Attachments help, but must be uploaded before submission and within file size limits)",
      "Step 6: Submit Before Deadline - Your application must be submitted before the official deadline (normally around June each year for the upcoming award cycle). Once submitted: You will usually receive acknowledgement, You cannot modify it after submission unless you request edits before the deadline (technical support can reopen your form)",
      "Step 7: Evaluation & Shortlist - All submissions go through a multi-stage evaluation: 1. Pre-screening & due diligence (ensures minimum criteria met) 2. Selection Committee review (shortlisting) 3. Jury evaluation — final winners are selected unanimously. Winners are announced at the award ceremony, usually held during Abu Dhabi Sustainability Week",
    ],
    documentsRequired: [
      "Organization/School registration details",
      "Project description & impact evidence",
      "Pitch narrative (Impact | Innovation | Inspiration)",
      "Supporting documents (photos, reports, data, or optional video link)",
      "Contact & founder/leader identity details",
    ],
    applyUrl: "https://zayedsustainabilityprize.com/en/",
    processingTime: "6-8 months (annual cycle to announcement)",
    keyPoints: [
      "USD 600K per category; 6 categories",
      "Focus on sustainability impact",
      "Annual deadline ~June; active 2025 cycle",
    ],
  },
  {
    id: 26,
    name: "UNICEF Venture Fund",
    shortName: "UNICEF Fund",
    category: "international",
    oneLiner: "The UNICEF Venture Fund is a global equity-free funding mechanism managed by UNICEF Innovation that invests in early-stage, open-source technology startups whose solutions advance children’s rights and wellbeing.",
    description: "Equity-free grants of USD 50K-400K for open-source tech impacting children.",
    fullDescription: "Supports early/growth-stage with mentorship, piloting, and global networks; thematic calls.",
    detailedBenefits: [
      "Equity-Free Capital - Direct funding to accelerate solution development without taking equity in the startup",
      "Funding Amount - USD 50,000–100,000 for early-stage startups, and USD 200,000–400,000 for growth-stage startups",
      "Global Market Access - Exposure through UNICEF’s extensive global networks, country offices, and partners",
      "Technical & Strategic Support - Access to mentoring, sector expertise, impact measurement tools, and development guidance aligned with UNICEF programmes",
      "Ecosystem Visibility - Opportunity to be featured on UNICEF platforms and connected to other funders, governments, and international organisations",
      "Implementation Pathway - Possibility of piloting solutions in UNICEF programmes and priority countries, leading to real deployment impact",
    ],
    detailedEligibility: [
      "Technology Focus & Impact - The solution should leverage technology with clear potential to impact children’s lives in areas such as health, education, protection, inclusion, and equity. Must demonstrate how the solution impacts children or youth (directly or indirectly)",
      "Open-Source Commitment - Solutions must be open source or be willing to adopt an open-source technology licensing model (e.g., MIT, BSD, Apache)",
      "Stage of Development - Typically early-stage to pre-Series A startups with a working prototype or MVP. Startups should show initial traction, product viability, and evidence of usage or impact",
      "Registered Entity - Must be a formally registered company or organisation, with founders and legal status documented",
      "Global Reach or Scalability - The solution should be scalable across geographies or adaptable to diverse communities, especially in low-resource settings",
    ],
    applicationProcess: [
      "For Early Stage - Month 0: Companies interested in applying to the Venture Fund need to check the eligibility criteria. Month 1: Companies interested should complete an online application via the Venture Fund website. The application form must include all required information and supporting documents as indicated. Month 2-3: The Venture Fund carefully assesses all applications. Shortlisted companies will then be notified and invited to submit a comprehensive proposal called the Request for Proposal (RFP). Month 4-5: Following a careful evaluation of the RFP, companies selected will be invited to an online demo interview. This 30-minute interview offers the opportunity to interact with the Venture Fund team and experts from our frontier technology teams. Month 6: Upon evaluating the application, RFP, and demo interview, the Venture Fund finalizes the investment decision and notifies selected companies. Onboarding begins, and an official announcement is made on public channels",
      "For Growth-Stage Funding - Early-stage graduation: Month 0: Growth-stage candidates must have completed the early-stage investment period with the Venture Fund to be eligible for Growth Funding. Invitation to Submit an EOI: Month 1: The Venture Fund team specifically invites thriving startups to seek growth-stage funding and submit an Expression of Interest (EOI). Request for Proposals: Month 2-3: Companies are shortlisted based on their Expressions of Interest and asked to submit a Request for Proposal to be considered for growth funding. Selection & Announcement of Investees: Month 4: The Venture Fund selection panel evaluate and select the companies that meet the established criteria. Selected companies are notified and the onboarding process starts, accompanied by an official announcement shared in public channels",
    ],
    documentsRequired: [
      "Company registration/incorporation certificates",
      "Legal entity details and team bios",
      "Proof of founders’ identities",
      "Technology stack description",
      "Prototype or MVP code repository links (GitHub, GitLab)",
      "Evidence of open-source licensing",
      "Description of problem and target population",
      "Evidence of social impact or pilot data",
      "Use cases and user testimonials (if available)",
      "Pitch deck (problem, solution, market, growth strategy)",
      "Scaling and operational roadmap",
      "Financial projections (if applicable)",
    ],
    applyUrl: "https://www.unicefventurefund.org/",
    processingTime: "4-6 months (multi-stage process)",
    keyPoints: [
      "Open-source required; child-impact focus",
      "Thematic calls; equity-free",
      "Active funding rounds in 2025",
    ],
  },
  {
    id: 27,
    name: "Microsoft for Startups (India)",
    shortName: "Microsoft Startups",
    category: "international",
    oneLiner: "Microsoft for Startups is a global program by Microsoft that offers startups access to technology credits, technical support, co-selling opportunities, and go-to-market resources to help them build, scale, and commercialize their products.",
    description: "Azure credits, mentorship, and go-to-market support for software startups.",
    fullDescription: "Investor-referred program; up to $150K Azure credits; co-selling with Microsoft.",
    detailedBenefits: [
      "Azure Cloud Credits & Technical Resources - Free or discounted Azure credits for infrastructure, data services, AI, and analytics. Technical support, best-practice guidance, and architecture reviews",
      "Go-To-Market Support - Marketing exposure through Microsoft’s channels. Access to co-selling and partner networks (including Azure Marketplace and AppSource). Joint campaign opportunities aligned with Microsoft sales teams",
      "Enterprise Customer Access - Introductions to enterprise customers via Microsoft ecosystem. Opportunity to be featured in Microsoft sales and partner interactions",
      "Technical Mentorship & Advisory - Guidance from Microsoft engineers and ecosystem partners. Workshops, technical sessions, and mentorship programs",
      "Networking & Community - Inclusion in startup ecosystems with access to Microsoft events, mentorship forums, and industry connections",
    ],
    detailedEligibility: [
      "Startup must be affiliated with an investor who is a part of the Microsoft for Startups Investor Network",
      "Startup is engaged in the development of a software-based product or service that is a core part of their current or intended business. The software must be owned and not licensed from another party",
      "Startup has received fewer than $350,000 in lifetime free Azure credits",
      "Startup is headquartered in a country where Azure services are available",
      "Startup hasn't raised Series C funding",
      "Startup is privately held",
      "Startup is a for-profit business",
      "Startup isn't an educational institution, government organization, personal blog, development shop, consultancy, agency, or involved in bitcoin or crypto mining",
    ],
    applicationProcess: [
      "Step 1: Obtain Referral - Once a startup receives their referral code from their investor, they should visit startups.microsoft.com, click 'Get started now,' and enter the referral code provided to you by your investor to begin the application process",
      "Step 2: Choose the Appropriate Development Stage - During the application process, you're asked to choose the stage that best describes your startup's current state: Concept design, Prototyping, Building MVP, MVP in market, Established market",
      "Step 3: Application Review and Evaluation - On average, it takes three business days to review an application. Response times may be delayed if information in the application needs to be verified. You're notified via the email used to apply as soon as a decision is made",
      "Step 4: Onboarding - If approved, access credits, support, and resources immediately",
    ],
    documentsRequired: [
      "Company name and legal registration",
      "Website and product URL (if available)",
      "Founders and team details",
      "Location and contact information",
      "Description of the product or solution",
      "Current stage of development (MVP/production)",
      "Technology stack (especially Azure use cases)",
      "Target customers and value proposition",
      "Revenue model (if available)",
      "Growth plans and customer acquisition strategy",
      "Azure subscription ID (if already using cloud)",
      "GitHub or repository links (optional)",
    ],
    applyUrl: "https://www.microsoft.com/en-in/startups",
    processingTime: "3 business days (review)",
    keyPoints: [
      "Requires investor referral for full benefits",
      "Focus on software/AI; up to $150K credits",
      "India program active as of December 2025",
    ],
  },

 
];

const seedSchemes = async () => {
  try {
    await connectDB();
    console.log("✅ MongoDB Connected Successfully");
    await Scheme.deleteMany({});
    console.log("🗑️ Existing schemes deleted");

    const inserted = await Scheme.insertMany(schemesData);
    console.log(`✅ ${inserted.length} schemes inserted successfully!`);

    await mongoose.connection.close();
    console.log("👋 Database connection closed");

    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding database:", error.message);
    process.exit(1);
  }
};

seedSchemes();